### PR TITLE
Social page

### PR DESCRIPTION
**Pull request by solo-daemon**
fix OWASP-BLT/BLT#3560

### CODE REVIEW

**Comment by just-ary27** [comment]
Coupd you disable navigation?

**Comment by solo-daemon** [comment]
@just-ary27 will not redirect to any other URL except for twitter URLs since twitter is a single page app so page changes can happen but that will not lead to any security threats or redirect to a foreign website

**Comment by solo-daemon** [comment]
@just-ary27 The new pr wiil disable all navigation 


https://user-images.githubusercontent.com/65587505/226000039-b0a7b2fe-4142-4271-a278-05becd64d869.mp4

**Comment by just-ary27** [comment]
Nice work!

**Pull request merged**
