### PR TITLE
Fix #29: Add slider

### LINKED ISSUE #29: Integrate pricing / plans page
https://pub.dev/packages/carousel_slider

### PR DESCRIPTION
**Pull request by Sparsh1212**
In this PR I have added the carousel slider, which we can later customize to display the plans instead of the images that are shown in the template.
The plans page can be opened via the NavDrawer.

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@fredfalcon Please take a look.

**Comment by Sparsh1212** [comment]
@fredfalcon This package does not comes with null safety and also many other packages that we might use later will not come with this null safety check.
So to run the app with ignoring these checks, we have to use this command:
`flutter run --no-sound-null-safety`

**Comment by fredfalcon** [comment]
Thank you!  Going to try 4.0.0-nullsafety.0 - also the design is done for this in Figma 
7287C015-C31C-4ECF-8329-80CD444B83EE

**Comment by Sparsh1212** [comment]
> Thank you! Going to try 4.0.0-nullsafety.0 - also the design is done for this in Figma
> 7287C015-C31C-4ECF-8329-80CD444B83EE

The new design is awesome.

**Comment by fredfalcon** [comment]
Thanks!  I had fun making it.  Thanks for the wireframe.  Still have to work out the plan offerings.

**Comment by Sparsh1212** [comment]
> Thanks! I had fun making it. Thanks for the wireframe. Still have to work out the plan offerings.

I too enjoyed a lot while designing the wireframes. Let me know if I can help in any other way.

**Comment by fredfalcon** [comment]
This looks good so far.  I’ll merge it once the design is integrated with the carousel.

**Pull request closed without merging**
