### PR TITLE
Correct Bottom Navigation bar implementation and add items to nav

### PR DESCRIPTION
**Pull request by Sparsh1212**
Fixes: #10 and #8.
The new pages added have been intentionally kept empty, so that they could be edited further based on the design.

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@fredfalcon @souravbadami Please review.

**Review by souravbadami — APPROVED** [review]

**Comment by ankit2001** [comment]
Nice work @Sparsh1212 .

**Comment by fredfalcon** [comment]
Thank you!

**Comment by Sparsh1212** [comment]
Thanks @ankit2001 @fredfalcon

**Pull request merged**
