### PR TITLE
Fix #35, Code Coverage

### LINKED ISSUE #35: Github Actions for code coverage
Github actions for code coverage should be added in the repo

### PR DESCRIPTION
**Pull request by ankit2001**
This PR aims to add Code Coverage to the Dart Project.

Access token can be created at https://app.codecov.io/ 

We have to add Flutter repo to the code coverage site and upload this token in the settings as CODECOV_TOKEN.

Screenshot 2021-06-16 at 12 30 08 PM

Screenshot 2021-06-16 at 12 30 51 PM

Please review it @fredfalcon , @souravbadami . 
Thanks

### CODE REVIEW

**Comment by souravbadami** [comment]
@fredfalcon - Could you please take this up?

**Comment by fredfalcon** [comment]
I have setup the CODECOV_TOKEN - please update the code so that the Bitrise build passes

**Review by fredfalcon — CHANGES_REQUESTED** [review]
please see comments

**Comment by ankit2001** [comment]
will fix this soon.

**Comment by fredfalcon** [comment]
This seems like a lot of 3rd party dependencies.   Would prefer to not have that many to keep the app more secure.  Can we close this?

**Pull request closed without merging**
