### PR TITLE
Add Error Page and Fix #45

### LINKED ISSUE #45: Fix Error Page
[Figma Link](https://www.figma.com/file/s0xuxeU6O2guoWEfA9OElZ/Bugheist-Full-Design?node-id=487%3A2719)

error_page

### PR DESCRIPTION
**Pull request by ankit2001**
This PR aims to add an error page in the App and fix #45.

Please review it @fredfalcon, @souravbadami.
Thanks.

### CODE REVIEW

**Comment by fredfalcon** [comment]
The page looks good, but we don't need all of the extra connectivity plugins can you please remove those?
image

**Review by fredfalcon — CHANGES_REQUESTED** [review]
please remove connectivity plugins and just have a simple error page

**Comment by ankit2001** [comment]
@fredfalcon , where we will use this error page then. Can you please tell me its usecase?

**Comment by fredfalcon** [comment]
I was originally thinking it would be when there was an error in the app but we can have a toast for that.  Maybe this can be the page that happens after a bug is submitted.

**Pull request closed without merging**
