### PR TITLE
Create a debug version of apk on every PR merge

### LINKED ISSUE #209: User not able to login
User is taken to signup page after login option from modals is selected .

### LINKED ISSUE #209: Update the android workflow.
https://github.com/OWASP/BLT-Flutter/issues/3

### PR DESCRIPTION
**Pull request by solo-daemon**
fix OWASP/BLT#209  fix https://github.com/OWASP/BLT-Flutter/issues/340

### CODE REVIEW

**Review by fredfalcon — APPROVED** [review]

**Review by justary27 — CHANGES_REQUESTED** [review]
This will not add a release file on merging the PR, kindly update accordingly.

**Comment by solo-daemon** [comment]
@fredfalcon the new repo isn't maintaining the commit history

**Comment by just-ary27** [comment]
@solo-daemon any updates on this?

**Review by justary27 — CHANGES_REQUESTED** [review]
Also rename the apk file to blt.apk

**Review by fredfalcon — APPROVED** [review]

**Review by justary27 — CHANGES_REQUESTED** [review]
This workflow will fail on running. I suggest you to think on this.

**Comment by DonnieBLT** [comment]
is this working?

**Pull request closed without merging**
