### PR TITLE
UI Fix on Monthly Leaderboard #287

### LINKED ISSUE #3497: Task: UI Fix on Monthly Leaderboard

### PR DESCRIPTION
**Pull request by zaeemkhan1999**
All three points done as asked in the issue.
Screenshot 2024-01-07 at 11 11 08 PM

### CODE REVIEW

**Comment by letsintegreat** [comment]
Can you please link the issue that is supposed to be solved by merging this PR right in the description? This helps reviewers quickly take a look at the issue's requirements. Another PR for reference: https://github.com/OWASP/BLT-Flutter/pull/318

**Comment by zaeemkhan1999** [comment]
Fixes #287

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
See comment

**Review by DonnieBLT — CHANGES_REQUESTED** [review]
Can you please fix the conflicts

**Pull request closed without merging**
