### PR TITLE
Fixed upvoted issues section on Profile page for anonymous user

### LINKED ISSUE #171: The upvoted issue section for anonymous user fails
WhatsApp Image 2023-02-26 at 23 06 05

The reason for this is the initiated upvotedIsuueId fot guestUser hence it was removed .

### PR DESCRIPTION
**Pull request by solo-daemon**
fix #171

### CODE REVIEW

**Comment by solo-daemon** [comment]
WhatsApp Image 2023-02-26 at 23 06 05

These are the after results .

**Comment by solo-daemon** [comment]
WhatsApp Image 2023-02-26 at 23 18 39 (1)

This is  the after result

**Review by just-ary27 — CHANGES_REQUESTED** [review]
I suggest adding some working issues, instead of the empty list, as guest login is meant to show all of app functionality.

**Comment by solo-daemon** [comment]
Then we suggest we add hardcoded elements for it otherwise we need to be sure the issue id's we are using as even if the if the api's fixed we will not be able to show anything to anonymous user . @just-ary27 . I will be updating the pr shortly

**Comment by solo-daemon** [comment]
@fredfalcon so should I make it hardcoded or hit for an anonymous user api . In case of hardcoded I will ensure the entire flow is visible .

**Comment by solo-daemon** [comment]
@just-ary27 I have created custom issue for our user which has been upvoted and saved . I have given it an id of -1 because the django backend never uses and id of -1 These are the results . 

WhatsApp Image 2023-02-27 at 18 36 04 (1)

WhatsApp Image 2023-02-27 at 18 36 04

**Comment by just-ary27** [comment]
@solo-daemon I think it will be better if you show the first page of the paginated response from the list api, this way it's more relevant & also ensures that issue showed are valid always.

**Comment by solo-daemon** [comment]
@just-ary27 Ok I will be working on it .

**Comment by solo-daemon** [comment]
@just-ary27 turns out it was a problem with listview builder actutally in the both the list view builder of the profile page there was no condition for when the description is less than 24 characters and hence was the error . So there are two chages 

1) Fixing the listviewbuilder
2) Now for the anonymous user we present him the first pagination issue page content in both the upvoted issue and saved issue .

**Review by just-ary27 — APPROVED** [review]

**Pull request merged**
